spring:
  datasource:
    url: ${ SPRING_DATASOURCE_URL }
    username: ${ SPRING_DATASOURCE_USERNAME }
    password: ${ SPRING_DATASOURCE_PASSWORD }
    driverClassName: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.localhost/realms/gestion-stock
          jwk-set-uri: http://keycloak:8095/realms/gestion-stock/protocol/openid-connect/certs
          jws-algorithms: RS256

gestion-stock:
  security:
    allowed-origins:
      - http://localhost
      - http://localhost:80
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
    allowed-headers:
      - Authorization
      - Content-Type