name: Create version

on:
  workflow_dispatch:
    inputs:
      current-version:
        description: 'Current version. Format (1.0)'
        required: true
      next-version:
        description: 'Prochaine version. Format (1.0-SNAPSHOT)'
        required: true

permissions:
  contents: write
  packages: write

jobs:
  tag-current-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name github-actions[bot]
          git config user.email "github-actions[bot]}@users.noreply.github.com"

      - name: Maven update current-version
        run: mvn versions:set -DnewVersion="${{ github.event.inputs.current-version }}" -DgenerateBackupPoms=false

      - name: Add git tag and push
        run: |
          git tag "v${{ github.event.inputs.current-version }}"
          git push origin --tags
          git commit -a -m "Release v${{ github.event.inputs.current-version }}"
          git push origin master

  create-push-docker-images:
    needs: tag-current-version
    uses: ./.github/workflows/create-push-docker-images.yml
    with:
      version: ${{ github.event.inputs.current-version }}

  prepare-next-version:
    needs: create-push-docker-images
    runs-on: ubuntu-latest
    steps:
      - name: Maven prepare next-version
        run: mvn versions:set -DnewVersion="${{ github.event.inputs.next-version }}" -DgenerateBackupPoms=false

      - name: Push next version
        run: |
          git commit -a -m "Setup v${{ github.event.inputs.next-version }}"
          git push origin master
